import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Lora } from "next/font/google";

const lora = Lora({
	subsets: ["latin"],
	weight: ["400", "500", "700"],
	variable: "--font-lora",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR" suppressHydrationWarning>
			<body
				className={`${lora.variable} antialiased flex flex-col min-h-screen bg-white text-gray-900 dark:bg-neutral-900 dark:text-white transition-colors`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="light"
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
