import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

import { Header } from "@/components/header";
import { FloatingNavbar } from "@/components/floating-navbar";

import { Lora } from "next/font/google"

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-lora", 
  display: "swap",
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${lora.variable} antialiased flex flex-col h-screen`} 
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col h-full">
            <Header />
            <main className="flex-1 overflow-y-auto pt-16 pb-24">
              {children}
            </main>
            <div className="fixed bottom-0 left-0 right-0 z-50 flex justify-center pb-4">
              <FloatingNavbar />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}